title: Wolkowski Web Design | Medicine Hat
email: contact@wolkowskiwebdesign.com

description: >- # this means to ignore newlines until "baseurl:"
    Wolkowski Web Design is based in Medicine Hat, Alberta. We specialize in creating beautiful, responsive, and functional websites..
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: 
github_username:

host: 0.0.0.0
sass: 
    sass_dir: /assets/css/_sass
    style: compressed

paginate: 2
paginate_path: "/articles/page:num/"
permalink: pretty

# Build settings
markdown: kramdown
plugins:
    - jekyll-minifier
    - jekyll-sitemap
include: ["_landing-page", "_redirects", "_contests"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
